version: "3.8"

services:
  api:
    build:
      context: ./api
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - QUEUE_NAME=${QUEUE_NAME}
    depends_on:
      - redis
    ports:
      - "8000:8000"
    command: uvicorn app:app --host 0.0.0.0 --port 8000

  worker:
    build:
      context: ./worker
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - QUEUE_NAME=${QUEUE_NAME}
    depends_on:
      - redis
    command: python worker.py

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"